# Generated by Django 4.2.14 on 2024-07-31 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_available_products_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='personalization_image',
            new_name='main_img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imgsProduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='link_of_nfc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='personalization_document',
        ),
    ]
