# Generated by Django 4.2.14 on 2024-07-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_mainimg_remove_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
