# Generated by Django 4.2.14 on 2024-07-31 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
